name: Test & Deploy CMS

on:
  push:
    paths: "Content-Management-Api/**"

jobs:
  Unit_Test:
    runs_on: composer-latest
    defaults:
      run:
        working-directory: ./Content-Management-Api/
    steps:
      - uses: actions/checkout@v2
      - name: Restore Dependencies
        run: composer install
      - name: Run Unit Tests
        run: ./vendor/bin/phpunit
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: ./**/junit.xml

  Deploy:
    if: success()
    runs_on: composer-latest
    defaults:
      run:
        working-directory: ./Content-Management-Api/
    steps:
      - uses: actions/checkout@v2
      - name: Restore Dependencies
        run: composer install --no-dev
