name: Test & Deploy Live Image Hosting Service

on:
  push:
    paths: "Image-Hosting-Service/**"
    branches:
      - main

jobs:
  Unit_Test:
    runs-on: ubuntu-latest
    container: rust:latest
    defaults:
      run:
        working-directory: ./Image-Hosting-Service/
    steps:
      - uses: actions/checkout@v2
      - name: Install Junit Reporter
        run: cargo install cargo2junit
      - name: Run Unit Tests
        run: cargo test -- -Z unstable-options --format json --report-time >> cargo_test.json
      - name: Convert to Junit
        run: cat cargo_test.json | cargo2junit >> junit.xml
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: ./**/junit.xml

  Build:
    needs: Unit_Test
    runs-on: ubuntu-latest
    container: rust:latest
    defaults:
      run:
        working-directory: ./Image-Hosting-Service/
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --release
      # Need to work out the specifics of deploying the rust executable
      # Ssh is probs the best bet
      # May need to x-compile for a specific target to match the uni env
      # - name: Deploy Application
      #   uses: SamKirkland/FTP-Deploy-Action@4.2.0
      #   with:
      #     server: ${{ secrets.FTP_SERVER }}
      #     username: ${{ secrets.FTP_USER }}
      #     password: ${{ secrets.FTP_PASSWORD }}
      #     local-dir: ./Woodiwiss-Consultants-Web/dist/woodiwiss-consultants-web/
      #     server-dir: ./dev/ui/
