name: Test & Deploy Image Hosting Service

on:
  push:
    paths: "Image-Hosting-Service/**"
    branches:
      - main

jobs:
  Unit_Test:
    runs-on: ubuntu-latest
    container: rust:latest
    defaults:
      run:
        working-directory: ./Image-Hosting-Service/
    steps:
      - uses: actions/checkout@v2
      - name: Install Junit Reporter
        run: cargo install cargo2junit
      - name: Run Unit Tests
        run: cargo test -- -Z unstable-options --format json --report-time >> cargo_test.json
      - name: Convert to Junit
        run: cat cargo_test.json | cargo2junit >> junit.xml
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: ./**/junit.xml

  Build:
    needs: Unit_Test
    runs-on: ubuntu-latest
    container: rust:latest
    defaults:
      run:
        working-directory: ./Image-Hosting-Service/
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Secrets
        env:
          SETTINGS: ${{ secrets.IHS_SECRETS_CONFIG_DEV }}
        run: |
          mkdir dist
          echo "$SETTINGS" > settings.b64
          cat settings.b64 | base64 -d > config.secrets.json
      - name: Build
        run: |
          cargo build --release
          cp ./target/release/image-hosting-service ./dist
          cp ./*.json ./dist
      - name: Stop Image Hosting Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SERVER }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            echo "${{ secrets.VPS_PASSWORD }}" | sudo -S service image-hosting stop
      - name: Deploy Application
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.VPS_SERVER }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          local-dir: ./Image-Hosting-Service/dist/
          server-dir: ./ihs-app/
      - name: Restart Image Hosting Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SERVER }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd ~/ihs-app/
            chmod +x image-hosting-service
            echo "${{ secrets.VPS_PASSWORD }}" | sudo -S service image-hosting start
